abstract class MainState {}
class InitMainState extends MainState{}
class  RequestAddCardState extends MainState{}
class  RequestAddFamilyState extends MainState{}
class  RequestUpdateFamilyState extends MainState{}
class  RequestUpdateCardState extends MainState{}
class  ProfileState extends MainState{}
class  MyProfileState extends MainState{}
class  AddFamilyEmptyState extends MainState{}
class  AddAcptedState extends MainState{}
class  AddRegctedState extends MainState{}
class  AddCardEmptyState extends MainState{}
class UpdateFamilyEmptyState extends MainState{}
class  UpdateCardEmptyState extends MainState{}
class  EmptyState extends MainState{}